import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import LandingPage from '../components/LandingPage'
import Showcase from './Showcase'
import Navbar from '../components/Navbar/index'
import {Switch,useColorMode} from "@chakra-ui/react"

export async function getStaticProps() {
  const response = await axios.get("http://localhost:3000/api/profile")
  const profile = await response.data
  return{
    props: { profile },
  }
}

export default function Home({profile}) {
  const {colorMode, toggleColorMode} = useColorMode()
  return (
    <div className={styles.container}>
      <Head>
        <title>{profile[0].name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Navbar />
      </nav>
        <div className='profile'>
          <LandingPage profile={profile}/>
        </div>
        <div className="toggleDarkMode">
        <Switch onChange={toggleColorMode} onClick={'/shocase'}>DarkMode {colorMode == "light" ? "off" : "on"}</Switch>
        </div>
      </div>
  )
}
